In [35]:
#text classification-models-
#sentiment classification
#https://realpython.com/python-keras-text-classification/
#Dataset    

In [36]:
#https://archive.ics.uci.edu/ml/datasets/Sentiment+Labelled+Sentences

In [37]:
import pandas as pd

filepath_dict = {'questions':   'data/intention_data/Dataset_classInt.csv'}

                 
df_list = []
for source, filepath in filepath_dict.items():
    df = pd.read_csv(filepath, encoding = "latin1",names=['sentence', 'label'], sep=',')
    df['source'] = source  # Add another column filled with the source name
    df_list.append(df)

df = pd.concat(df_list)
print(df.shape)
print(df.iloc[20])

(1113, 3)
sentence    Is this a bot?
label                    1
source           questions
Name: 20, dtype: object


In [38]:
#Basic classifier
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer

#select only df_yelp

sentences = df['sentence'].values
y = df['label'].values
print(len(y))

1113


In [39]:
sentences_train, sentences_test, y_train, y_test = train_test_split(sentences, y, test_size=0.25, random_state=1000)

In [40]:
#create td-idf vectors
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()
vectorizer.fit(sentences_train)

#add feature for test
X_train = vectorizer.transform(sentences_train)
X_test  = vectorizer.transform(sentences_test)
X_train

<834x436 sparse matrix of type '<class 'numpy.int64'>'
	with 5784 stored elements in Compressed Sparse Row format>

In [41]:
#classify with logisticRegresion
from sklearn.linear_model import LogisticRegression
logistic_classifier = LogisticRegression()
logistic_classifier.fit(X_train, y_train)
score = logistic_classifier.score(X_test, y_test)
print("Accuracy:", score)

Accuracy: 0.921146953405018


c:\users\memo_\documents\proyectos\python\text_mining\text_mining_venv\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
c:\users\memo_\documents\proyectos\python\text_mining\text_mining_venv\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


In [49]:
logistic_y_pred = logistic_classifier.predict(X_test)
logistic_y_pred

array([ 8, 16, 15, 11, 10, 11,  8,  1, 19, 11,  8, 10, 16,  8, 10, 20, 11,
       18, 20, 13, 17,  0, 19, 20, 18, 11, 15,  8, 17, 11, 16,  9, 17, 11,
       19, 11,  9, 18, 11, 11,  1, 18, 12, 16, 15, 12,  8, 19, 12, 18, 10,
       20, 10, 15, 19, 10, 16, 13,  8, 11, 11, 11, 12, 18,  9, 18,  8, 15,
        8, 13, 20,  8, 11,  8, 15, 13, 17, 11, 12,  1, 18, 19,  8, 12, 17,
       18, 13, 18, 11, 11, 20, 11, 13, 19, 13, 19, 11,  9,  8, 12, 11, 16,
        8, 20, 18, 11, 13, 13, 19, 18, 11,  8,  7, 13,  8, 19, 11, 10, 20,
       20, 11, 10,  8, 16, 11, 18, 19, 18, 13, 11, 16, 11,  6, 12, 20,  8,
       17, 15,  8,  8, 19, 15,  8, 11,  8, 11,  9, 17,  9, 11, 10,  0, 16,
        1, 12,  8, 11, 18, 18, 13, 15, 11, 11,  0,  8, 11, 18,  4, 20, 11,
        8, 13,  9, 18,  9,  9,  8, 13,  8, 20, 13, 11, 13,  4, 16,  8, 11,
        8, 17,  8,  9,  8, 19, 19, 12,  8, 11,  6,  9, 16, 17, 13,  8, 13,
        3, 10, 11, 16, 17,  9, 13,  8,  8, 19, 20, 19,  8, 18, 20, 11, 15,
       12, 20,  8, 18, 11

In [50]:
from sklearn.metrics import classification_report
print(classification_report(y_test, logistic_y_pred))


              precision    recall  f1-score   support

           0       0.60      1.00      0.75         3
           1       1.00      0.75      0.86         8
           3       1.00      1.00      1.00         1
           4       1.00      0.67      0.80         3
           5       0.00      0.00      0.00         1
           6       1.00      1.00      1.00         2
           7       1.00      0.50      0.67         2
           8       0.81      0.97      0.89        36
           9       1.00      1.00      1.00        12
          10       1.00      1.00      1.00        15
          11       0.91      0.93      0.92        54
          12       0.85      0.79      0.81        14
          13       1.00      1.00      1.00        20
          14       0.00      0.00      0.00         1
          15       1.00      0.92      0.96        12
          16       0.86      1.00      0.92        12
          17       0.93      0.72      0.81        18
          18       0.96    

In [51]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, logistic_y_pred))

[[ 3  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  6  0  0  0  0  0  2  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  2  0  0  0  1  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  1  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  2  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  1  1  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 1  0  0  0  0  0  0 35  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0 12  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0 15  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0 50  2  0  0  0  0  1  0  1  0]
 [ 0  0  0  0  0  0  0  0  0  0  3 11  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 20  0  0  0  0  0  0  0]
 [ 1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0 11  1  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 12  0  0